# Generated by Django 5.1.3 on 2024-11-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Тавар атауы')),
                ('description', models.TextField(verbose_name='Сипаттама')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бағасы')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған уақыты')),
            ],
        ),
    ]
